-- DROP TABLES

-- Clear staging tables from ddl_dml.sql
DROP TABLE IF EXISTS CARDS;
DROP TABLE IF EXISTS ACCOUNTS;
DROP TABLE IF EXISTS CLIENTS;

-- CARDS
DROP TABLE IF EXISTS STG_CARDS;
DROP TABLE IF EXISTS STG_NOT_MATCHED_ROWS_CARDS;
DROP TABLE IF EXISTS STG_MATCHED_ROWS_CARDS;
DROP TABLE IF EXISTS STG_NEW_ROWS_CARDS;
DROP TABLE IF EXISTS STG_DELETED_ROWS_CARDS;
DROP TABLE IF EXISTS STG_CHANGED_ROWS_CARDS;

-- ACCOUNTS
DROP TABLE IF EXISTS STG_ACCOUNTS;
DROP TABLE IF EXISTS STG_NOT_MATCHED_ROWS_ACCOUNTS;
DROP TABLE IF EXISTS STG_MATCHED_ROWS_ACCOUNTS;
DROP TABLE IF EXISTS STG_NEW_ROWS_ACCOUNTS;
DROP TABLE IF EXISTS STG_DELETED_ROWS_ACCOUNTS;
DROP TABLE IF EXISTS STG_CHANGED_ROWS_ACCOUNTS;

-- CLIENTS
DROP TABLE IF EXISTS STG_CLIENTS;
DROP TABLE IF EXISTS STG_NOT_MATCHED_ROWS_CLIENTS;
DROP TABLE IF EXISTS STG_MATCHED_ROWS_CLIENTS;
DROP TABLE IF EXISTS STG_NEW_ROWS_CLIENTS;
DROP TABLE IF EXISTS STG_DELETED_ROWS_CLIENTS;
DROP TABLE IF EXISTS STG_CHANGED_ROWS_CLIENTS;

-- DIM tables between staging and final DIM tables
DROP TABLE IF EXISTS DWH_DIM_CARDS;
DROP TABLE IF EXISTS DWH_DIM_CLIENTS;
DROP TABLE IF EXISTS DWH_DIM_ACCOUNTS;

-- TERMINALS
DROP TABLE IF EXISTS STG_TERMINALS;
DROP TABLE IF EXISTS STG_NEW_ROWS_TERMINALS;
DROP TABLE IF EXISTS STG_DELETED_ROWS_TERMINALS;
DROP TABLE IF EXISTS STG_CHANGED_ROWS_TERMINALS;

-- TRANSACTIONS
DROP TABLE IF EXISTS STG_TRANSACTIONS;

-- PASSPORT_BLACKLIST
DROP TABLE IF EXISTS STG_PASSPORT_BLACKLIST;

-- REP_FRAUD
DROP TABLE IF EXISTS STG_REP_FRAUD;
DROP VIEW IF EXISTS STG_DETECTION_FRAUD_DIFFERENT_CITY;
DROP VIEW IF EXISTS STG_DETECTION_FRAUD_SUM_UP;